include:
    - docker-compose.yml
services:
    database:
        image: postgres
        environment:
            POSTGRES_DB: testapp
            POSTGRES_PASSWORD: password
            POSTGRES_USER: testapp
        volumes:
            - db_data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
volumes:
    db_data:
