### Calculate Price
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "productId": 3,
  "taxNumber": "GR123456789",
  "couponCode": "perc6"
}

### Execute Purchase
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "productId": 3,
  "taxNumber": "DE123456789",
  "couponCode": "perc6",
  "paymentProcessor": "paypal"
}
